--- # install java and install jenkins
- hosts: webservers
  become: yes
  user: ansible
  connection: ssh

  tasks:
    - name: install java s/w
      yum:
        name: java
        state: present

    - name: install wget command
      yum:
        name: wget
        state: installed
    - name: download jenkins s/w
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo 

    - name: jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: install jenkins
      yum:
        name: jenkins
        state: installed

    - name: start jenkins service 
      service:
        name: jenkins
        state: started
        enabled: yes
